openapi: 3.2.0
info:
  title: absentify CRUD Public holidays API
  description: OpenAPI compliant REST API
  version: 1.0.0
servers:
- url: https://api.absentify.com/api/v1
tags:
- name: Public Holidays
paths:
  /public_holidays:
    get:
      operationId: publicHolidays-getPublicHolidays
      summary: Get all public holidays
      tags:
      - Public Holidays
      security:
      - ApiKey: []
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    createdAt:
                      type: string
                    updatedAt:
                      type: string
                    country_code:
                      anyOf:
                      - type: string
                      - type: 'null'
                    county_code:
                      anyOf:
                      - type: string
                      - type: 'null'
                    public_holiday_days:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          date:
                            type: string
                          year:
                            type: number
                          custom_value:
                            type: boolean
                          duration:
                            type: string
                            enum:
                            - Morning
                            - Afternoon
                            - FullDay
                          updatedAt:
                            type: string
                          createdAt:
                            type: string
                          public_holiday_day_languages:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: string
                                name:
                                  type: string
                                language:
                                  type: string
                              required:
                              - id
                              - name
                              - language
                              additionalProperties: false
                        required:
                        - id
                        - date
                        - year
                        - custom_value
                        - duration
                        - updatedAt
                        - createdAt
                        - public_holiday_day_languages
                        additionalProperties: false
                  required:
                  - id
                  - name
                  - createdAt
                  - updatedAt
                  - country_code
                  - county_code
                  - public_holiday_days
                  additionalProperties: false
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BAD_REQUEST'
        '401':
          description: Authorization not provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UNAUTHORIZED'
        '403':
          description: Insufficient access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.FORBIDDEN'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NOT_FOUND'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.INTERNAL_SERVER_ERROR'
  /public_holidays/{id}:
    get:
      operationId: publicHolidays-getPublicHolidayById
      summary: Read a public holiday by id
      tags:
      - Public Holidays
      security:
      - ApiKey: []
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
          pattern: ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                anyOf:
                - type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    createdAt:
                      type: string
                    updatedAt:
                      type: string
                    country_code:
                      anyOf:
                      - type: string
                      - type: 'null'
                    county_code:
                      anyOf:
                      - type: string
                      - type: 'null'
                    public_holiday_days:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          date:
                            type: string
                          year:
                            type: number
                          custom_value:
                            type: boolean
                          duration:
                            type: string
                            enum:
                            - Morning
                            - Afternoon
                            - FullDay
                          updatedAt:
                            type: string
                          createdAt:
                            type: string
                          public_holiday_day_languages:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: string
                                name:
                                  type: string
                                language:
                                  type: string
                              required:
                              - id
                              - name
                              - language
                              additionalProperties: false
                        required:
                        - id
                        - date
                        - year
                        - custom_value
                        - duration
                        - updatedAt
                        - createdAt
                        - public_holiday_day_languages
                        additionalProperties: false
                  required:
                  - id
                  - name
                  - createdAt
                  - updatedAt
                  - country_code
                  - county_code
                  - public_holiday_days
                  additionalProperties: false
                - type: 'null'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BAD_REQUEST'
        '401':
          description: Authorization not provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UNAUTHORIZED'
        '403':
          description: Insufficient access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.FORBIDDEN'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NOT_FOUND'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.INTERNAL_SERVER_ERROR'
components:
  schemas:
    error.BAD_REQUEST:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: Invalid input data
        code:
          type: string
          description: The error code
          example: BAD_REQUEST
        issues:
          description: An array of issues that were responsible for the error
          example: []
          type: array
          items:
            type: object
            properties:
              message:
                type: string
            required:
            - message
            additionalProperties: false
      required:
      - message
      - code
      additionalProperties: false
      title: Invalid input data error (400)
      description: The error information
      example:
        code: BAD_REQUEST
        message: Invalid input data
        issues: []
    error.UNAUTHORIZED:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: Authorization not provided
        code:
          type: string
          description: The error code
          example: UNAUTHORIZED
        issues:
          description: An array of issues that were responsible for the error
          example: []
          type: array
          items:
            type: object
            properties:
              message:
                type: string
            required:
            - message
            additionalProperties: false
      required:
      - message
      - code
      additionalProperties: false
      title: Authorization not provided error (401)
      description: The error information
      example:
        code: UNAUTHORIZED
        message: Authorization not provided
        issues: []
    error.INTERNAL_SERVER_ERROR:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: Internal server error
        code:
          type: string
          description: The error code
          example: INTERNAL_SERVER_ERROR
        issues:
          description: An array of issues that were responsible for the error
          example: []
          type: array
          items:
            type: object
            properties:
              message:
                type: string
            required:
            - message
            additionalProperties: false
      required:
      - message
      - code
      additionalProperties: false
      title: Internal server error error (500)
      description: The error information
      example:
        code: INTERNAL_SERVER_ERROR
        message: Internal server error
        issues: []
    error.FORBIDDEN:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: Insufficient access
        code:
          type: string
          description: The error code
          example: FORBIDDEN
        issues:
          description: An array of issues that were responsible for the error
          example: []
          type: array
          items:
            type: object
            properties:
              message:
                type: string
            required:
            - message
            additionalProperties: false
      required:
      - message
      - code
      additionalProperties: false
      title: Insufficient access error (403)
      description: The error information
      example:
        code: FORBIDDEN
        message: Insufficient access
        issues: []
    error.NOT_FOUND:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: Not found
        code:
          type: string
          description: The error code
          example: NOT_FOUND
        issues:
          description: An array of issues that were responsible for the error
          example: []
          type: array
          items:
            type: object
            properties:
              message:
                type: string
            required:
            - message
            additionalProperties: false
      required:
      - message
      - code
      additionalProperties: false
      title: Not found error (404)
      description: The error information
      example:
        code: NOT_FOUND
        message: Not found
        issues: []
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-API-KEY
      in: header
    BearerAuth:
      type: http
      scheme: bearer
      description: 'The API key as `Authorization: Bearer <key>`.'
externalDocs:
  url: https://absentify.com/docs/en/api-reference
